# Stress-test agents. Each StressAgent generates traffic at a Poisson rate
# (mix of topic broadcasts and directed messages to random peers) and keeps an
# exact ledger of everything it sent and received, keyed by (sender, stream, seq).

# Unix-epoch wall-clock ms: Java's System.currentTimeMillis() uses the Unix epoch
# while Fjage.currenttimemillis uses the Dates epoch (year 0), so cross-language
# latency must be computed on this clock.
unixms() = round(Int64, 1000 * time())

@agent struct StressAgent
  rate::Float64 = 1.0                 # msgs/s (mean) generated by this agent
  peers::Vector{String} = String[]    # names of the other participants
  ready::Bool = false                 # set once startup (incl. subscribe) has run
  active::Bool = false                # senders gated on this
  lat_from::Int64 = typemax(Int64)    # record latency only for msgs with t0 ≥ this
  # churn mode: the primary behavior only adds/removes secondary sender behaviors
  churn::Bool = false
  secondaries::Vector{Fjage.Behavior} = Fjage.Behavior[]   # currently live
  spawned::Vector{Fjage.Behavior} = Fjage.Behavior[]       # every secondary ever added
  churn_adds::Int64 = 0
  churn_removes::Int64 = 0
  # sender-side ledger
  bcast_sent::Int64 = 0
  dm_sent::Dict{String,Int64} = Dict{String,Int64}()
  send_fail::Int64 = 0
  # receiver-side ledger
  seen::Dict{Tuple{String,String},BitSet} = Dict{Tuple{String,String},BitSet}()
  dups::Int64 = 0
  latencies::Vector{Int64} = Int64[]
end

function _send_stress!(a::StressAgent)
  if rand() < 0.5
    a.bcast_sent += 1
    msg = StressMsg(recipient=topic("stress"), stream="b", seq=a.bcast_sent)
  else
    p = rand(a.peers)
    n = get(a.dm_sent, p, 0) + 1
    a.dm_sent[p] = n
    msg = StressMsg(recipient=AgentID(p), stream="d", seq=n)
  end
  msg.t0 = unixms()
  send(a, msg) || (a.send_fail += 1)
end

# churn: every ~500 ms randomly spawn or stop a secondary sender (0-6 live);
# each secondary sends at rate/3, so with ~3 live on average the agent's total
# load ≈ rate. Stopping behaviors that are mid-block is the point — it exercises
# the block/restart/stop protocol continuously.
const CHURN_TARGET = 3.0
const CHURN_MAX = 6

function _churn!(a::StressAgent)
  if isempty(a.secondaries) || (rand() < 0.5 && length(a.secondaries) < CHURN_MAX)
    sb = PoissonBehavior(max(1, round(Int64, 1000CHURN_TARGET / a.rate))) do a, b
      a.active && _send_stress!(a)
    end
    push!(a.secondaries, sb)
    push!(a.spawned, sb)
    a.churn_adds += 1
    add(a, sb)
  else
    sb = popat!(a.secondaries, rand(1:length(a.secondaries)))
    a.churn_removes += 1
    stop(sb)
  end
end

function Fjage.startup(a::StressAgent)
  subscribe(a, topic("stress"))
  if a.churn
    add(a, PoissonBehavior(500) do a, b
      a.active && _churn!(a)
    end)
  else
    add(a, PoissonBehavior(max(1, round(Int64, 1000 / a.rate))) do a, b
      a.active || return
      _send_stress!(a)
    end)
  end
  # note: built via the 1-arg ctor + field assignment because master's
  # MessageBehavior(action, filt) convenience ctor is broken (passes 8 args to a
  # 9-field struct; fixed on fix-block-race) and this harness must run on both
  mb = MessageBehavior() do a, b, msg
    s = msg.sender === nothing ? "?" : name(msg.sender)
    s == name(a) && return    # own topic broadcasts come back to us; ignore
    bs = get!(BitSet, a.seen, (s, msg.stream))
    if msg.seq ∈ bs
      a.dups += 1
    else
      push!(bs, msg.seq)
      msg.t0 ≥ a.lat_from && push!(a.latencies, unixms() - msg.t0)
    end
  end
  mb.filt = StressMsg
  mb.priority = -100
  add(a, mb)
  a.ready = true
end

sent_total(a::StressAgent) = a.bcast_sent + sum(values(a.dm_sent); init=0)
recv_total(a::StressAgent) = sum(length.(values(a.seen)); init=0) + a.dups

# Bare agent used in slave mode as the endpoint for the control exchange with
# the Java jagent (send/request are agent operations; the orchestrator isn't one).
@agent struct CtlAgent end
